# The data in the metadata file here defines inputs, outputs, and entrypoint

name: "Hello Actions"
description: "Greet someone"
author: "davenlu1989@gmail.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"